name: on-premise-cicd      # Github Actions 목록에서 보여지는 이름
on:                         # 언제 방아쇠를 당겨서 워크플로우를 실행할지 정의
  workflow-dispatch:
    inputs:
      tags:                 # 태그로 어떤 버전인지 확인하기 위해 사용 (ex: v1.0.0)
        description: 'Set Tags Name'
        required: true
        default: main       # 깃헙의 main 브랜치

jobs:
  build:
    runs-on: ubuntu-latest  # 가상머신 종류
    outputs:                # 리턴 값
      release: ${{ steps.set-version.outputs.VERSION_NAME }}  # 버전 명시
    steps:
        # v1.0.0 -> v1-0-0 으로 변경 >> GITHUB_OUTPUT 변수에 할당
        # github(=on), event(=workflow-dispatch)
      - id: set-version
        run: |
          echo "VERSION_NAME=$(echo "${{ github.event.inputs.tags }}" | sed "s/\./\-/g")" >> $GITHUB_OUTPUT

      - name: Check Version Name
        run: | 
          echo "Check Version -> ${{ steps.set-version.outputs.VERSION_NAME }}"

        # 배포할 check out 소스
        # github marketplace 의 공식 checkout 액션 (작성법 : actions/액션명@버전)
        # ㄴ ex) 4.17버전일 경우 v4로 작성 가능
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:   # 파라미터
          ref: '${{ github.event.inputs.tags }}'

      - name: Grant execute permission for gradlew
        run: chmod +w gradlew

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

        # gradle 빌드
        # 위치 : 위의 checkout 으로 현재 프로젝트안에 위치 -> 현재 위치의 /gradlew 를 실행
      - name: Build with Gradlew
        run: ./gradlew clean test bootJar   # clean -> test -> bootJar 순서로 실행

        # 위의 clean -> test -> bootJar 를 실행하면 -> build/libs 하위에 생성된 .jar 파일을 add
      - name: Add version
        run: | 
          mv build/libs/community_feed-1.0-SNAPSHOT.jar build/libs/community_feed-${{ steps.set-version.outputs.VERSION_NAME }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: community_feed-application  # community_feed-application.zip 파일로 ci runner 공간에 저장
          path: build/libs/community_feed-${{ steps.set-version.outputs.VERSION_NAME }}.jar